[package]
name = "rls-remote"
version = "0.1.0"
authors = ["Nate Mara <nate.mara@kroger.com>"]

[dependencies]
tokio-core = "0.1.12"
futures = "0.1.18"
tokio-io = "0.1.4"
tokio-stdin-stdout = "0.1.1"
